services:
  bots:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bots
    env_file:
      - ../.env
    volumes:
      - ../bots.db:/app/bots.db
    command: "python3 main.py"
