FROM python:3.13.5-alpine3.22

WORKDIR /app
RUN pip install poetry 
RUN poetry config virtualenvs.create false
COPY ../pyproject.toml ../poetry.lock ./
RUN poetry install --only main --no-root
ADD .. .


