# generated by datamodel-codegen:
#   filename:  http://testserver.ua/openapi.json
#   timestamp: 2025-07-16T09:44:49+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from aiogram import F
from pydantic import BaseModel, Field


class AuthLogin(BaseModel):
    success: Optional[str] = Field("ok", title="Success")
    url: str = Field(..., title="Url")


class BaseStats(BaseModel):
    battles: int = Field(..., title="Battles")
    winrate: float = Field(..., title="Winrate")
    damage: float = Field(..., title="Damage")
    accuracy: float = Field(..., title="Accuracy")
    survival: float = Field(..., title="Survival")
    avg_xp: float = Field(..., title="Avg Xp")
    wins_and_survived: float = Field(..., title="Wins And Survived")
    murder_to_murder: float = Field(..., title="Murder To Murder")
    damage_coefficient: float = Field(..., title="Damage Coefficient")


class BodyAddTankAdminAddTankPost(BaseModel):
    tank_id: int = Field(..., title="Tank Id")
    name: str = Field(..., title="Name")
    nation: str = Field(..., title="Nation")
    tier: int = Field(..., title="Tier")
    is_premium: bool = Field(..., title="Is Premium")
    image_big: Optional[bytes] = Field(None, title="Image Big")
    image_small: Optional[bytes] = Field(None, title="Image Small")


class ClanTop(BaseModel):
    region: str = Field(..., title="Region")
    name: str = Field(..., title="Name")
    clan_id: int = Field(..., title="Clan Id")
    tag: str = Field(..., title="Tag")
    general_battles: int = Field(..., title="General Battles")
    general_wins: float = Field(..., title="General Wins")
    averageDamage: float = Field(..., title="Averagedamage")
    rating: float = Field(..., title="Rating")


class CombatStats(BaseModel):
    timestamp: List[int] = Field(
        ..., description="Дата события или матча", title="Timestamp"
    )
    damage: List[float] = Field(..., description="Нанесённый урон", title="Damage")
    wins: List[float] = Field(..., description="Количество побед", title="Wins")
    survival: List[float] = Field(
        ..., description="Выживаемость, от 0 до 1", title="Survival"
    )
    battles: List[int] = Field(..., description="Количество боёв", title="Battles")
    accuracy: List[float] = Field(
        ..., description="Точность стрельбы", title="Accuracy"
    )


class Commands(Enum):
    field_reset_user = "!reset_user"
    field_reset_clan = "!reset_clan"
    field_delete_user = "!delete_user"
    field_delete_clan = "!delete_clan"
    field_update_player_db = "!update_player_db"
    field_update_clan_db = "!update_clan_db"


class ErrorResponse(BaseModel):
    detail: str = Field(..., title="Detail")


class Images(BaseModel):
    preview: Optional[str] = Field(None, title="Preview")
    normal: Optional[str] = Field(None, title="Normal")


class LoginForm(BaseModel):
    username: str = Field(..., title="Username")
    password: str = Field(..., title="Password")


class Medal(BaseModel):
    name: str = Field(..., title="Name")
    image: Optional[str] = Field("undefined", title="Image")
    count: int = Field(..., title="Count")


class Medals(BaseModel):
    medals: Optional[List[Medal]] = Field([], title="Medals")


class Parameter(Enum):
    battles = "battles"
    wins = "wins"
    damage = "damage"


class Private(BaseModel):
    gold: Optional[int] = Field(0, title="Gold")
    ban_info: Optional[str] = Field(None, title="Ban Info")
    free_xp: Optional[int] = Field(0, title="Free Xp")
    ban_time: Optional[int] = Field(None, title="Ban Time")
    is_premium: bool = Field(..., title="Is Premium")
    credits: Optional[int] = Field(0, title="Credits")
    premium_expires_at: Optional[int] = Field(0, title="Premium Expires At")
    battle_life_time: Optional[int] = Field(0, title="Battle Life Time")


class Rating(BaseModel):
    spotted: int = Field(..., title="Spotted")
    calibration_battles_left: int = Field(..., title="Calibration Battles Left")
    hits: int = Field(..., title="Hits")
    frags: int = Field(..., title="Frags")
    recalibration_start_time: int = Field(..., title="Recalibration Start Time")
    mm_rating: float = Field(..., title="Mm Rating")
    wins: int = Field(..., title="Wins")
    losses: int = Field(..., title="Losses")
    is_recalibration: bool = Field(..., title="Is Recalibration")
    capture_points: int = Field(..., title="Capture Points")
    battles: int = Field(..., title="Battles")
    current_season: int = Field(..., title="Current Season")
    damage_dealt: int = Field(..., title="Damage Dealt")
    damage_received: int = Field(..., title="Damage Received")
    shots: int = Field(..., title="Shots")
    frags8p: int = Field(..., title="Frags8P")
    xp: int = Field(..., title="Xp")
    win_and_survived: int = Field(..., title="Win And Survived")
    survived_battles: int = Field(..., title="Survived Battles")
    dropped_capture_points: int = Field(..., title="Dropped Capture Points")
    score: Optional[int] = Field(..., title="Score")
    number: Optional[int] = Field(..., title="Number")


class Region(Enum):
    eu = "eu"
    asia = "asia"
    com = "com"
    na = "na"


class RestPrivate(BaseModel):
    gold: int = Field(..., title="Gold")
    free_xp: int = Field(..., title="Free Xp")
    credits: int = Field(..., title="Credits")
    is_premium: bool = Field(..., title="Is Premium")
    premium_expires_at: int = Field(..., title="Premium Expires At")
    battle_life_time: int = Field(..., title="Battle Life Time")


class RestRating(BaseModel):
    battles: int = Field(..., title="Battles")
    winrate: float = Field(..., title="Winrate")
    damage: float = Field(..., title="Damage")
    accuracy: float = Field(..., title="Accuracy")
    survival: float = Field(..., title="Survival")
    avg_xp: float = Field(..., title="Avg Xp")
    wins_and_survived: float = Field(..., title="Wins And Survived")
    murder_to_murder: float = Field(..., title="Murder To Murder")
    damage_coefficient: float = Field(..., title="Damage Coefficient")
    score: Optional[int] = Field(..., title="Score")
    number: Optional[int] = Field(..., title="Number")


class RestStatsTank(BaseModel):
    battles: int = Field(..., title="Battles")
    winrate: float = Field(..., title="Winrate")
    damage: float = Field(..., title="Damage")
    accuracy: float = Field(..., title="Accuracy")
    survival: float = Field(..., title="Survival")
    avg_xp: float = Field(..., title="Avg Xp")
    wins_and_survived: float = Field(..., title="Wins And Survived")
    murder_to_murder: float = Field(..., title="Murder To Murder")
    damage_coefficient: float = Field(..., title="Damage Coefficient")
    profit_coefficient: float = Field(..., title="Profit Coefficient")


class RestUserDB(BaseModel):
    region: Region
    name: str = Field(..., title="Name")
    player_id: int = Field(..., title="Player Id")


class StatsTank(BaseModel):
    spotted: Optional[int] = Field(0, title="Spotted")
    hits: Optional[int] = Field(0, title="Hits")
    frags: Optional[int] = Field(0, title="Frags")
    max_xp: Optional[int] = Field(0, title="Max Xp")
    wins: Optional[int] = Field(0, title="Wins")
    losses: Optional[int] = Field(0, title="Losses")
    capture_points: Optional[int] = Field(0, title="Capture Points")
    battles: Optional[int] = Field(0, title="Battles")
    damage_dealt: Optional[int] = Field(0, title="Damage Dealt")
    damage_received: Optional[int] = Field(0, title="Damage Received")
    max_frags: Optional[int] = Field(0, title="Max Frags")
    shots: Optional[int] = Field(0, title="Shots")
    frags8p: Optional[int] = Field(0, title="Frags8P")
    xp: Optional[int] = Field(0, title="Xp")
    win_and_survived: Optional[int] = Field(0, title="Win And Survived")
    survived_battles: Optional[int] = Field(0, title="Survived Battles")
    dropped_capture_points: Optional[int] = Field(0, title="Dropped Capture Points")
    damage: float = Field(..., title="Damage")
    winrate: float = Field(..., title="Winrate")
    accuracy: float = Field(..., title="Accuracy")
    survival: float = Field(..., title="Survival")
    avg_xp: float = Field(..., title="Avg Xp")
    wins_and_survived: float = Field(..., title="Wins And Survived")
    murder_to_murder: float = Field(..., title="Murder To Murder")
    damage_coefficient: float = Field(..., title="Damage Coefficient")


class TopPlayer(BaseModel):
    region: Region
    name: str = Field(..., title="Name")
    player_id: int = Field(..., title="Player Id")
    parameter: Parameter
    value: Union[float, int] = Field(..., title="Value")


class AdminStats(BaseModel):
    uptime_seconds: int = Field(..., title="Uptime Seconds")
    user_count: int = Field(..., title="User Count")
    clan_count: int = Field(..., title="Clan Count")
    last_players_update: datetime = Field(..., title="Last Players Update")
    last_clan_update: datetime = Field(..., title="Last Clan Update")
    count_active_users: int = Field(..., title="Count Active Users")
    active_users_list: List[RestUserDB] = Field(..., title="Active Users List")
    external_api_calls: int = Field(..., title="External Api Calls")
    custom_api_calls: Dict[str, int] = Field(..., title="Custom Api Calls")
    last_1000_logs: List[Dict[str, Any]] = Field(..., title="Last 1000 Logs")


class Command(BaseModel):
    command: Commands
    region: Optional[Region] = None
    arguments: Optional[str] = Field("", title="Arguments")


class CreateTank(BaseModel):
    tank_id: int = Field(..., title="Tank Id")
    name: str = Field(..., title="Name")
    nation: str = Field(..., title="Nation")
    tier: int = Field(..., title="Tier")
    is_premium: bool = Field(..., title="Is Premium")
    images: Optional[Images] = Field(None, title="Images")


class ItemTank(BaseModel):
    all: Optional[RestStatsTank]
    nation: str = Field(..., title="Nation")
    images: Images
    name: str = Field(..., title="Name")
    level: Union[int, str] = Field(..., title="Level")
    is_premium: bool = Field(..., title="Is Premium")
    last_battle_time: int = Field(..., title="Last Battle Time")
    tank_id: int = Field(..., title="Tank Id")


class RestStatistics(BaseModel):
    rating: Optional[RestRating] = None
    all: Optional[RestStatsTank] = None


class Statistics(BaseModel):
    rating: Optional[Rating]
    all: Optional[StatsTank]


class General(BaseModel):
    update: Optional[RestStatistics] = Field(None, title="Update")
    now: Optional[RestStatistics] = Field(None, title="Now")
    session: Optional[RestStatistics] = Field(None, title="Session")


class GeneralTanks(BaseModel):
    update: Optional[List[ItemTank]] = Field(None, title="Update")
    now: Optional[List[ItemTank]] = Field(None, title="Now")
    session: Optional[List[ItemTank]] = Field(None, title="Session")


class PlayerModel(BaseModel):
    nickname: str = Field(..., title="Nickname")
    account_id: Optional[int] = Field(0, title="Account Id")
    created_at: Optional[int] = Field(0, title="Created At")
    updated_at: Optional[int] = Field(0, title="Updated At")
    private: Optional[Private]
    statistics: Statistics
    last_battle_time: Optional[int] = Field(0, title="Last Battle Time")


class RestMember(BaseModel):
    id: int = Field(..., title="Id")
    nickname: str = Field(..., title="Nickname")
    general: Optional[RestStatistics] = None
    last_battle_time: Union[int, str] = Field(..., title="Last Battle Time")


class RestUser(BaseModel):
    region: Region
    name: str = Field(..., title="Name")
    player_id: int = Field(..., title="Player Id")
    time: int = Field(..., title="Time")
    private: Optional[RestPrivate]
    general: General
    tanks: Optional[GeneralTanks]
    medals: Medals


class ClanDB(BaseModel):
    region: str = Field(..., title="Region")
    name: str = Field(..., title="Name")
    clan_id: int = Field(..., title="Clan Id")
    tag: str = Field(..., title="Tag")
    members_count: int = Field(..., title="Members Count")
    members: List[PlayerModel] = Field(..., title="Members")
    timestamp: Optional[int] = Field(None, title="Timestamp")


class RestClan(BaseModel):
    region: str = Field(..., title="Region")
    name: str = Field(..., title="Name")
    clan_id: int = Field(..., title="Clan Id")
    tag: str = Field(..., title="Tag")
    members_count: int = Field(..., title="Members Count")
    members: List[RestMember] = Field(..., title="Members")
    general: BaseStats
    time: int = Field(..., title="Time")
